name: Snyk Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Snyk
        run: npm install -g snyk
      - name: Run Snyk test
        run: snyk test --json-file-output=.github/snyk-result.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
      - name: List files
        run: ls -la
        
      - name: Save Snyk results in JSON
        run: snyk test --json-file-output=.github/snyk-result.json || true

      - name: Convert Snyk JSON to PDF
        run: |
          pip install fpdf
          python .github/snyk_to_pdf.py
          
      - name: Upload PDF report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.pdf
